### ISSUE TITLE
Add gitter link for dongyue

### ISSUE THREAD

**Issue by at15** [SJTU-SE/activities-for-you#5]
鉴于 join@dongyue.io 没有设置转发，回复会很慢，就建了一个 gitter 的 room

https://gitter.im/dyweb/digger?utm_source=share-link&utm_medium=link&utm_campaign=share-link
- [ ] 添加到 README
- [ ] gitter 的 badge 

(我懒得同步自己的 fork 了 cc @arrowrowe

**Comment by arrowrowe** [comment]
join@dongyue.io 设立之初就转发到全体招新组个人邮箱.

昨天那个没收到的是发到 dongyue.webstudio (at) gmail.com 了.

**Comment by gaocegege** [comment]
嗯哼

**Comment by gaocegege** [comment]
那我先close了
